import Button from "../components/button/Button";

export const columnsData = [
  {
    name: "Title",
    value: "title",
    order: 1,
  },
  {
    name: "Category",
    value: "category",
    order: 2,
  },
  {
    name: "Price",
    value: "price",
    order: 3,
  },
  {
    name: "Year",
    value: "year",
    order: 4,
  },
  {
    name: "Author",
    value: "author",
    order: 5,
  },
  {
    name: "Status",
    value: "status",
    order: 6,
  },
  {
    name: "Action",
    action: () => <Button />,
    order: 7,
  },
];

export const data = [
  {
    id: 1,
    title: "Blue Jeans",
    category: "Clothing",
    price: 45,
    year: "2023",
    author: "John Doe",
    status: "Available",
  },
  {
    id: 2,
    title: "Leather Jacket",
    category: "Apparel",
    price: 150,
    year: "2022",
    author: "Jane Smith",
    status: "Sold",
  },
  {
    id: 3,
    title: "Sneakers",
    category: "Footwear",
    price: 80,
    year: "2024",
    author: "Alex Johnson",
    status: "Available",
  },
  {
    id: 4,
    title: "Sunglasses",
    category: "Accessories",
    price: 30,
    year: "2023",
    author: "Emma Brown",
    status: "Available",
  },
  {
    id: 5,
    title: "Trench Coat",
    category: "Outerwear",
    price: 200,
    year: "2022",
    author: "Michael Wilson",
    status: "Pending",
  },
  {
    id: 6,
    title: "Hoodie",
    category: "Sweatshirts",
    price: 60,
    year: "2024",
    author: "Sophia Lee",
    status: "Available",
  },
  {
    id: 7,
    title: "Formal Dress",
    category: "Dresses",
    price: 120,
    year: "2023",
    author: "David Garcia",
    status: "Sold",
  },
  {
    id: 8,
    title: "Beanie",
    category: "Headwear",
    price: 20,
    year: "2022",
    author: "Olivia Martinez",
    status: "Available",
  },
  {
    id: 9,
    title: "Wristwatch",
    category: "Accessories",
    price: 100,
    year: "2024",
    author: "Ethan Taylor",
    status: "Available",
  },
  {
    id: 10,
    title: "T-shirt",
    category: "Tops",
    price: 25,
    year: "2023",
    author: "Ava Anderson",
    status: "Pending",
  },
];
